name: openstack
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_3
  - pip=20.0.2=py38_1
  - python=3.8.1=h359304d_1
  - readline=7.0=h1de35cc_5
  - setuptools=45.1.0=py38_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.1=py38_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appdirs==1.4.3
    - attrs==19.3.0
    - babel==2.8.0
    - cffi==1.13.2
    - chardet==3.0.4
    - cliff==2.18.0
    - cmd2==0.8.9
    - cryptography==2.8
    - debtcollector==1.22.0
    - decorator==4.4.1
    - dogpile-cache==0.9.0
    - idna==2.8
    - iso8601==0.1.12
    - jmespath==0.9.4
    - jsonpatch==1.25
    - jsonpointer==2.0
    - jsonschema==3.2.0
    - keystoneauth1==3.18.0
    - msgpack==0.6.2
    - munch==2.5.0
    - netaddr==0.7.19
    - netifaces==0.10.9
    - openstacksdk==0.40.0
    - os-service-types==1.7.0
    - osc-lib==2.0.0
    - oslo-config==7.0.0
    - oslo-i18n==3.25.1
    - oslo-serialization==2.29.2
    - oslo-utils==3.42.1
    - pbr==5.4.4
    - prettytable==0.7.2
    - pycparser==2.19
    - pyopenssl==19.1.0
    - pyparsing==2.4.6
    - pyperclip==1.7.0
    - pyrsistent==0.15.7
    - python-cinderclient==5.0.0
    - python-glanceclient==2.17.0
    - python-keystoneclient==3.22.0
    - python-novaclient==16.0.0
    - python-openstackclient==4.0.0
    - pytz==2019.3
    - pyyaml==5.3
    - requests==2.22.0
    - requestsexceptions==1.4.0
    - rfc3986==1.3.2
    - simplejson==3.17.0
    - six==1.14.0
    - stevedore==1.31.0
    - urllib3==1.25.8
    - warlock==1.3.3
    - wcwidth==0.1.8
    - wrapt==1.11.2
prefix: /usr/local/Caskroom/miniconda/base/envs/openstack

